### ISSUE TITLE
Error when clicking "detail" on network

### ISSUE THREAD

**Issue by twisteroidambassador** [key-networks/ztncui-containerized#9]
In the "Networks" tab, clicking on the "detail" link of a network results in the following error messages:

```
TypeError: /snapshot/src/views/controller_layout.pug:21
    19|       .collapse.navbar-collapse(id='BarNav')
    20|         ul.nav.navbar-nav
  > 21|           li(class=(nav.active === 'controller_home'? 'active' : ''))
    22|             a(href='/controller') Home
    23|           li(class=(nav.active === 'users'? 'active' : ''))
    24|             a(href='/users') Users

Cannot read property 'active' of undefined
    at eval (eval at wrap (/snapshot/src/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:53:73)
    at template (eval at wrap (/snapshot/src/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:104:225)
    at Object.exports.renderFile (/snapshot/src/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/snapshot/src/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/snapshot/src/node_modules/pug/lib/index.js:464:11)
    at View.render (/snapshot/src/node_modules/express/lib/view.js:135:8)
    at tryRender (/snapshot/src/node_modules/express/lib/application.js:640:10)
    at Function.render (/snapshot/src/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/snapshot/src/node_modules/express/lib/response.js:1008:7)
    at /snapshot/src/app.js:0:0
```

Running in a Docker image built locally by cloning the repo and doing a `docker build`.

**Comment by twisteroidambassador** [comment]
This error does not happen with the docker image pulled directly from `keynetworks/ztncui`. Version of `zerotier-one` inside this image is 1.2.12, while the image built directly from the docker file would have the latest `zerotier-one`, currently 1.4.2. Would this be the reason?

**Comment by key-networks** [comment]
No, it's not a problem with zerotier-one - I think it's a bug in one of the dependencies of ztncui.  If I run ztncui from source on my laptop (my development machine running Fedora 30) with zerotier-one-1.4.2, there is no problem.  But if I run the source on an Ubuntu 18.04 VM with zerotier-one-1.4.2, the above error occurs.  I have updated the dependencies, but still the same problem.  Very odd.

**Comment by key-networks** [comment]
We have cross-reporting of this issue here https://github.com/key-networks/ztncui/issues/20

**Comment by key-networks** [comment]
The problem was not checking whether or not the element of an array was defined when listing network details.  I've uploaded new packages for version 0.5.8 - please test them and give me your feedback.

**Comment by twisteroidambassador** [comment]
Yup, rebuilding from the latest dockerfile solves the issue. Thanks!
